# Any username in this list is invalid
INVALID_USERNAMES = ['admin',
                     'admins',
                     'administrador',
                     'administradors',
                     'administradores',
                     'administrator',
                     'administrators',
                     'coordenador',
                     'coordenadors',
                     'coordenadores',
                     'coordinator',
                     'coordinators',
                     'departamento',
                     'departamentos',
                     'departamentais',
                     'departamental',
                     'departamentals',
                     'department',
                     'departmental',
                     'departmentals',
                     'departments',
                     'supervisor',
                     'supervisors',
                     'supervisores']
