# Generated by Django 2.1.7 on 2019-04-27 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190426_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caderneta',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cadernetas', to='core.Student')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cadernetas', to='core.StudyPlan')),
            ],
            options={
                'db_table': 'school_cadernetas',
                'ordering': ['-created_at'],
            },
        ),
    ]
