# Generated by Django 2.1.7 on 2019-04-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190427_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningobjective',
            name='is_optional',
        ),
        migrations.AddField(
            model_name='learningobjective',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Determine if the objective is mandatory'),
        ),
    ]
