# Generated by Django 2.1.5 on 2019-01-23 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190123_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_published',
        ),
    ]
