# Generated by Django 2.1.5 on 2019-02-03 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190123_0440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
