# Generated by Django 2.1.5 on 2019-02-03 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190202_2323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostLikes',
            new_name='PostLike',
        ),
    ]
