# Generated by Django 2.1.5 on 2019-02-04 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190204_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='supervisor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plans', to='core.Instructor'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='plan',
            table='plan',
        ),
    ]
