# Generated by Django 2.1.7 on 2019-03-26 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190204_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='supervisor',
            new_name='instructor',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='student',
        ),
        migrations.RemoveField(
            model_name='planner',
            name='instructor',
        ),
        migrations.AddField(
            model_name='plan',
            name='IEP',
            field=models.FileField(blank=True, upload_to='plans/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='plan',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='minimum_grade_required',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Published'), ('R', 'For Review'), ('C', 'Cancelled')], default='D', max_length=2),
        ),
        migrations.AddField(
            model_name='planner',
            name='user',
            field=models.ForeignKey(default=466872904880, on_delete=django.db.models.deletion.DO_NOTHING, related_name='planners', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='plans',
            field=models.ManyToManyField(to='core.Plan'),
        ),
        migrations.AlterModelTable(
            name='plan',
            table='student_plans',
        ),
        migrations.AlterModelTable(
            name='planner',
            table='user_planners',
        ),
    ]
