# Generated by Django 2.1.7 on 2019-03-26 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190326_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannerEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to='core.Planner')),
            ],
            options={
                'db_table': 'user_planner_entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
