# Generated by Django 2.1.7 on 2019-03-26 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_plannerentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='creator',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_plans', to='core.Instructor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='managed_plans', to='core.Instructor'),
        ),
    ]
