# Generated by Django 2.1.7 on 2019-03-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_totp', '0001_initial'),
        ('two_factor', '0005_auto_20160224_0450'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('otp_static', '0001_initial'),
        ('authtoken', '0002_auto_20160226_1747'),
        ('core', '0013_auto_20190326_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='plans',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_ptr',
        ),
        migrations.AlterField(
            model_name='plannerentry',
            name='id',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
