# Generated by Django 2.1.7 on 2019-03-27 01:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190326_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannerentry',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
