# Generated by Django 2.1.7 on 2019-03-28 22:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20190328_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='planner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='core.Planner'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Textual Notes', null=True, verbose_name='Textual Notes'),
        ),
    ]
