# Generated by Django 2.1.7 on 2019-04-05 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20190328_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Agenda'},
        ),
        migrations.AlterModelOptions(
            name='plannerentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.ForeignKey(default=466872904880, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='title',
            field=models.CharField(default='Title', max_length=244),
            preserve_default=False,
        ),
    ]
