# Generated by Django 2.1.7 on 2019-04-09 01:27

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20190405_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='guests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_guests',
            },
            bases=('core.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('is_required', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=256)),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'learning_modules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['-created_at'], 'permissions': (('can_create_plans', 'Can create student plans'),)},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-created_at'], 'permissions': (('can_create_plan', 'Can create plan'),)},
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Event', max_length=144),
        ),
        migrations.AddField(
            model_name='module',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='modules', to='core.Plan'),
        ),
    ]
