# Generated by Django 2.1.7 on 2019-04-09 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20190409_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_number',
            new_name='student_id',
        ),
    ]
