# Generated by Django 2.1.7 on 2019-04-09 19:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20190409_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyModule',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('study-modules', models.FileField(blank=True, upload_to='study-modules/%Y/%m/%d/')),
                ('minimum_grade_required', models.PositiveIntegerField(default=50)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='managed_plans', to='core.Instructor')),
            ],
            options={
                'db_table': 'study_modules',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyModuleRequirement',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.StudyModule')),
            ],
            options={
                'db_table': 'study_module_requirements',
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='module',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='IEP',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='content',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='minimum_grade_required',
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.AddField(
            model_name='studymodule',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.StudyPlan'),
        ),
    ]
