# Generated by Django 2.1.7 on 2019-04-11 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20190409_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymodule',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='managed_modules', to='core.Instructor'),
        ),
    ]
