from django.contrib import admin
from .user import UserAdmin
from .event import EventAdmin
from .instructor import InstructorAdmin
from .logs import LogEntryAdmin
from .study_plan import StudyPlanAdmin
from .planner import PlannerAdmin
from .student import StudentAdmin
from .post import PostAdmin
from .enrollment import Enrollment
from .course import Course
from .comment import Comment
from .role import Role
from .term import Term
from .waitlist import Waitlist
from .gradebook import Gradebook
